name: CaveTeleport
version: 1.1
main: com.xinglingqaq.CaveTeleport

permissions:
  caveteleport.pass:
    description: 允许玩家触发洞穴传送
    default: op
  caveteleport.reload:
    description: 允许重载插件配置
    default: op

commands:
  ctp:
    description: 重载插件配置
    usage: /ctp reload
    permission: caveteleport.reload

api-version: 1.16