name: StarTeleport
version: 1.3
main: com.xinglingqaq.StarTeleport

permissions:
  starteleport.pass:
    description: 允许玩家触发传送
    default: op
  starteleport.command.reload:
    description: 允许重载插件配置
    default: op

commands:
  stp:
    description: 重载插件配置
    usage: /stp reload
    permission: starteleport.command.reload

api-version: 1.16