name: NovaTeleport
version: 2.0-SNAPSHOT
main: com.novamclabs.StarTeleport
api-version: 1.16
folia-supported: true
softdepend: [Vault, PlaceholderAPI, floodgate, Geyser, Parties, BetterTeams, SimpleClans, Factions, Guilds, WorldGuard, PlotSquared, Residence, Lands, GriefDefender, Towny]

permissions:
  novateleport.pass:
    description: 允许玩家触发世界阈值传送
    default: op
  novateleport.command.reload:
    description: 允许重载插件配置
    default: op
  novateleport.admin:
    description: NovaTeleport 管理员权限
    default: op
  novateleport.command.tpa:
    description: 使用 /tpa
    default: true
  novateleport.command.tpahere:
    description: 使用 /tpahere
    default: true
  novateleport.command.tpaccept:
    description: 使用 /tpaccept
    default: true
  novateleport.command.tpdeny:
    description: 使用 /tpdeny
    default: true
  novateleport.command.tpcancel:
    description: 使用 /tpcancel
    default: true
  novateleport.command.home:
    description: 使用 /home /sethome /delhome /homes
    default: true
  novateleport.command.warp:
    description: 使用 /warp /warps
    default: true
  novateleport.command.setwarp:
    description: 使用 /setwarp /delwarp
    default: op
  novateleport.command.spawn:
    description: 使用 /spawn
    default: true
  novateleport.command.back:
    description: 使用 /back
    default: true
  novateleport.command.rtp:
    description: 使用 /rtp
    default: true
  novateleport.economy.bypass:
    description: 免除传送费用
    default: op
  novateleport.animation.select:
    description: 允许玩家选择动画风格
    default: true
  novateleport.animation.tech:
    description: 解锁科技风格动画
    default: op
  novateleport.animation.natural:
    description: 解锁自然风格动画
    default: op
  novateleport.scroll.bind:
    description: 允许玩家绑定传送卷轴
    default: op
  novateleport.command.party:
    description: 使用 /party 组队命令
    default: true

  novateleport.command.tpmenu:
    description: 使用 /tpmenu 传送菜单
    default: true

  novateleport.guild.home:
    description: 使用 /gtp home 工会据点传送
    default: true
  novateleport.guild.admin:
    description: 管理工会据点/传送点
    default: op

  novateleport.towny.home:
    description: 传送到自己的城镇
    default: true
  novateleport.towny.other:
    description: 传送到其他城镇
    default: op

  novateleport.toll.create:
    description: 创建付费传送点
    default: true
  novateleport.toll.delete.others:
    description: 删除他人付费传送点
    default: op
  novateleport.toll.bypass:
    description: 付费传送点免付费
    default: op

  novateleport.admin.rewind:
    description: 使用 /tplog 回溯玩家传送
    default: op

commands:
  stp:
    description: 重载插件配置
    usage: /stp reload
    permission: novateleport.command.reload
  tpa:
    description: 请求传送到玩家
    usage: /tpa <玩家>
    permission: novateleport.command.tpa
  tpahere:
    description: 请求玩家传送到你
    usage: /tpahere <玩家>
    permission: novateleport.command.tpahere
  tpaccept:
    description: 接受传送请求
    usage: /tpaccept
    permission: novateleport.command.tpaccept
  tpdeny:
    description: 拒绝传送请求
    usage: /tpdeny
    permission: novateleport.command.tpdeny
  tpcancel:
    description: 取消自己发起的传送请求
    usage: /tpcancel
    permission: novateleport.command.tpcancel
  sethome:
    description: 设置家
    usage: /sethome [名称]
    permission: novateleport.command.home
  home:
    description: 回家
    usage: /home [名称]
    permission: novateleport.command.home
  delhome:
    description: 删除家
    usage: /delhome [名称]
    permission: novateleport.command.home
  setwarp:
    description: 设置公共传送点
    usage: /setwarp <名称>
    permission: novateleport.command.setwarp
  warp:
    description: 前往公共传送点（无参数打开菜单）
    usage: /warp [名称]
    permission: novateleport.command.warp
  delwarp:
    description: 删除公共传送点
    usage: /delwarp <名称>
    permission: novateleport.command.setwarp
  spawn:
    description: 前往出生点
    usage: /spawn
    permission: novateleport.command.spawn
  back:
    description: 返回上一个位置
    usage: /back
    permission: novateleport.command.back
  rtp:
    description: 随机传送（无参数打开菜单）
    usage: /rtp [now|start|半径]
    permission: novateleport.command.rtp
  tpanimation:
    description: 选择传送动画风格
    usage: /tpanimation select <magic|tech|natural>
    permission: novateleport.animation.select
  scroll:
    description: 传送卷轴指令
    usage: /scroll bind <home|warp> <名称>
    permission: novateleport.scroll.bind
  city:
    description: 回城
    usage: /city
    permission: novateleport.command.spawn
    aliases: [hub]
  novateleport:
    description: NovaTeleport 主命令
    usage: /novateleport <子命令>
    aliases: [ntp, novatp]
  party:
    description: 组队系统
    usage: /party <create|invite|accept|leave|tp>
    permission: novateleport.command.party
  stele:
    description: 传送石碑系统
    usage: /stele <list|locate|create|remove|travel|activatefor>
    permission: novateleport.admin
  deathback:
    description: 回到上次死亡位置
    usage: /deathback
    permission: novateleport.command.back
  forcetp:
    description: 强制传送离线玩家（控制台可用）
    usage: /forcetp <player> <world> <x> <y> <z>
    permission: novateleport.admin

  homes:
    description: 列出/选择我的家
    usage: /homes
    permission: novateleport.command.home

  warps:
    description: 列出/选择公共传送点
    usage: /warps
    permission: novateleport.command.warp

  rtpgui:
    description: 打开随机传送 GUI
    usage: /rtpgui
    permission: novateleport.command.rtp

  tpmenu:
    description: 打开传送菜单
    usage: /tpmenu
    permission: novateleport.command.tpmenu
    aliases: [tpm]

  gtp:
    description: 工会传送
    usage: /gtp <home|sethome|warp|setwarp|delwarp|list|info>
    permission: novateleport.guild.home

  towntp:
    description: Towny 城镇传送
    usage: /towntp [城镇名]
    permission: novateleport.towny.home

  tollwarp:
    description: 付费传送点
    usage: /tollwarp <list|mywarps|create|delete|setprice|tp|info>
    permission: novateleport.toll.create
    aliases: [publichomes]

  tplog:
    description: 传送日志与回溯
    usage: /tplog <玩家>
    permission: novateleport.admin.rewind
